language: objective-objective

osx_image: xcode10.1
env:
    matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iphone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iphone 7'
    
script:
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project MusicLib.xcodeproj -scheme MusicLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
